// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjPofJk87HBe9oiNQKZC3zbMNtHgRuKGE',
    appId: '1:1070977770620:web:3c25b804a5674f7ffd55f9',
    messagingSenderId: '1070977770620',
    projectId: 'pathshala-2023',
    authDomain: 'pathshala-2023.firebaseapp.com',
    storageBucket: 'pathshala-2023.appspot.com',
    measurementId: 'G-2BHN6EXTYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRFWNTyi4G9m3-7y7H4PImSlfZCqktI-c',
    appId: '1:1070977770620:android:cf017848156d8a83fd55f9',
    messagingSenderId: '1070977770620',
    projectId: 'pathshala-2023',
    storageBucket: 'pathshala-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARXk7EIwbvhlHXy31VcWVJOCBJ_LkOAWs',
    appId: '1:1070977770620:ios:58ec90d33cdecca0fd55f9',
    messagingSenderId: '1070977770620',
    projectId: 'pathshala-2023',
    storageBucket: 'pathshala-2023.appspot.com',
    iosBundleId: 'com.example.firstAttempt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARXk7EIwbvhlHXy31VcWVJOCBJ_LkOAWs',
    appId: '1:1070977770620:ios:3089fcbe9b2f246ffd55f9',
    messagingSenderId: '1070977770620',
    projectId: 'pathshala-2023',
    storageBucket: 'pathshala-2023.appspot.com',
    iosBundleId: 'com.example.firstAttempt.RunnerTests',
  );
}
